- name: Install app dependencies 
  action: apt pkg={{ item }} state=installed
  with_items:
    - libpq-dev
    - nodejs

- name: Create deployment user
  user: name=deploy comment="Application deployment user"

- name: Create deployment directory
  file: path=/home/deploy/{{ app_name }} owner=deploy group=deploy state=directory

